site_name: Knowledge Base - Nuclear.Hosting
site_url: https://nuclear.hosting/help/
site_description: Knowledge Base will help you to set up Nuclear.Hosting services. In the Knowledge Base you will find detailed information about the services, pictorial tutorials and answers to frequently asked questions.
site_author: Nuclear.Hosting (www.nuclear.hosting)
google_analytics: ['UA-92972843-3', 'nuclear.hosting/help/']

theme: readthedocs

markdown_extensions:
    - admonition
nav:
    - Home: index.md
    - How to start using Web Hosting: start.md
    - Websites: websites.md
    - HTTPS & Secured Web Access: https.md
    - MySQL Databases: mysql_databases.md
    - E-Mails: emails.md
    - Domains: domains.md
    - DNS: dns.md
    - Billing: billing.md
    - 1-Click Installer: oneclick.md
    - Wordpress: wordpress.md
    - PrestaShop: prestashop.md
    - Payments & Billing: billing.md
    - Files / Data manipulation: files.md
    - PHP Scripting: php.md
    - FTP/SFTP: ftp.md
    - CRON: cron.md
    - GIT / Gitlab: git.md
    - SSH / Shell: shell.md
    - WebSMTP: websmtp.md
    - Video Tutorials: video.md
    - Fair Usage Policy: fup.md
    - Backups: backups.md
    - Security: security.md