site_name: Nuclear.Hosting Knowledge Base
site_url: https://nuclear.hosting/help/
site_description: Nuclear.Hosting Knowledge Base
site_author: Nuclear.Hosting www.nuclear.hosting
google_analytics: ['UA-92972843-3', 'nuclear.hosting/help/']

theme: readthedocs

markdown_extensions:
    - admonition
nav:
    - Home: index.md
    - How to start using Web Hosting: start.md
    - Websites: websites.md
    - HTTPS & Secured Web Access: https.md
    - MySQL Databases: mysql_databases.md
    - E-Mails: emails.md
    - Domains: domains.md
    - DNS: dns.md
    - 1-Click Installer: oneclick.md
    - Wordpress: wordpress.md
    - Payments & Billing: billing.md
    - Files / Data manipulation: files.md
    - FTP/SFTP: ftp.md
    - GIT: git.md
    - SSH / Chroot: shell.md
    - Video Tutorials: video.md
    - PHP Scripting: php.md
    - Fair Usage Policy: fup.md
    - Backups: backups.md
    - Security: security.md